server:
  port: 8080
#  address: 172.20.10.2

spring:
  #数据库连接信息
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/acm
    username: root
    password: 111111
  #文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  #redis连接信息
  data:
    redis:
      host: 192.168.128.131
      port: 6379
      password: "031023"
      database: 0
      lettuce:
        pool:
          max-active: 8 #最大连接
          max-idle: 8 #最大空闲连接
          min-idle: 0 #最小空闲连接
          max-wait: 100ms #连接等待时间

#mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#阿里云OSS
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    accessKeyId: xxx
    accessKeySecret: xxx
    bucketName: web-test-aliyunoss

#Spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug